#!/usr/bin/env bash

# Seed this Kuiper checkout from a nightly (or release) binary package, so that
# a subsequent build only re-verifies the files that actually changed.
#
# It copies the prebuilt toolchain (inst/), the extraction plugin, and the
# verified library (obj/*.checked) out of a package into this checkout, marks
# the tree as `.packaged` (so make does not rebuild F*/Karamel from the
# submodules), and then lets F*'s content-hash-based incremental build figure
# out which .checked files are stale and rebuild exactly those (and whatever
# transitively depends on them).
#
# This avoids the ~10-minute `make prepare` toolchain build and re-verifies
# only your local changes.
#
# Usage:
#   scripts/seed-from-nightly.sh [OPTIONS]
#
# Package source (pick one; default: download the latest nightly):
#   --nightly            Download the latest nightly package (default)
#   --release            Download the latest release package
#   --version VER        A specific version (e.g. 2026-03-31 or v2026.03.24)
#   --tarball FILE       Use a local package tarball (kuiper-*.tar.gz)
#   --dir DIR            Use an already-extracted package tree (has inst/, obj/)
#
# After seeding:
#   --target T           Run `make T` after seeding (default: verify)
#   --no-build           Only seed; don't run make
#   -j N                 Parallelism for the build (default: nproc)
#   -h, --help           Show this help

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Defaults
SOURCE=nightly
VERSION=latest
TARBALL=
PKGDIR=
DO_BUILD=true
TARGET=verify
JOBS="$( (command -v nproc >/dev/null && nproc) || echo 4)"

usage() { sed -n '3,30p' "$0" | sed 's/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --nightly)   SOURCE=nightly; shift ;;
    --release)   SOURCE=release; shift ;;
    --version)   VERSION="${2:?--version needs an argument}"; shift 2 ;;
    --tarball)   TARBALL="${2:?--tarball needs an argument}"; shift 2 ;;
    --dir)       PKGDIR="${2:?--dir needs an argument}"; shift 2 ;;
    --target)    TARGET="${2:?--target needs an argument}"; shift 2 ;;
    --no-build)  DO_BUILD=false; shift ;;
    -j)          JOBS="${2:?-j needs an argument}"; shift 2 ;;
    -h|--help)   usage; exit 0 ;;
    *)           echo "Error: unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

msg() { printf '>>> %s\n' "$*" >&2; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

WORK="$(mktemp -d --tmpdir kuiper-seed.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

# --- Obtain a package tree in $PKG ----------------------------------------

if [ -n "$PKGDIR" ]; then
  PKG="$(cd "$PKGDIR" && pwd)"
  msg "Using package tree at $PKG"
elif [ -n "$TARBALL" ]; then
  TARBALL="$(realpath "$TARBALL")"
  [ -f "$TARBALL" ] || die "tarball not found: $TARBALL"
  PKG="$WORK/pkg"
  mkdir -p "$PKG"
  msg "Extracting $TARBALL"
  tar --no-same-owner -xzf "$TARBALL" --strip-components=1 -C "$PKG"
else
  PKG="$WORK/pkg"
  msg "Downloading latest $SOURCE package via install-kuiper.sh"
  args=( "--$SOURCE" --dest "$PKG" --no-link )
  [ "$VERSION" != latest ] && args+=( --version "$VERSION" )
  "$ROOT/scripts/install-kuiper.sh" "${args[@]}"
fi

# --- Sanity checks --------------------------------------------------------

[ -x "$PKG/inst/bin/fstar.exe" ] || die "$PKG/inst/bin/fstar.exe not found; not a Kuiper package?"
ls "$PKG"/obj/*.checked >/dev/null 2>&1 || die "no obj/*.checked in package; nothing to seed."
PKG_PLUGIN="$PKG/extraction/dune/_build/default/kuiper_extr.cmxs"
[ -f "$PKG_PLUGIN" ] || die "extraction plugin not found in package."

if [ -f "$PKG/BUILD_INFO" ]; then
  msg "Package build info:"
  sed 's/^/    /' "$PKG/BUILD_INFO" >&2
fi

# --- Seed the toolchain, plugin, and checked library ----------------------

msg "Seeding toolchain (inst/)"
rm -rf inst
cp -a "$PKG/inst" inst

msg "Seeding extraction plugin"
mkdir -p extraction/dune/_build/default
cp -a "$PKG_PLUGIN" extraction/dune/_build/default/

msg "Seeding verified library (obj/*.checked)"
mkdir -p obj
cp -a "$PKG"/obj/*.checked obj/

# Reuse the package's dependency graph; make will regenerate it if the source
# set changed (its prereqs are the source roots).
[ -f "$PKG/.depend" ] && cp -a "$PKG/.depend" .depend

# --- Generate autogenerated sources so the source set is complete ---------
# (Klas.SPMM.fst etc. are produced from .fst.sh scripts and are gitignored.)
while IFS= read -r sh; do
  fst="${sh%.sh}"
  if [ ! -f "$fst" ] || [ "$sh" -nt "$fst" ]; then
    msg "Generating $fst"
    "./$sh" > "$fst"
  fi
done < <(find src -name '*.fst.sh')

# --- Set up incremental-build timestamps ----------------------------------
#
# The package's obj/*.checked were built in dependency order, so (preserved by
# cp -a) their mtimes already form a consistent DAG: every checked file is newer
# than the checked files it depends on. We exploit make's mtime model directly:
#
#   * A source that is byte-identical to the package's copy has a valid checked
#     file, so we make that source OLDER than every checked file -> make skips it.
#   * A source that differs (or is new) gets a mtime of "now" -> make re-runs F*
#     on it, and, via the checked-vs-checked edges in .depend, on everything that
#     transitively depends on it. F*'s content hashing then re-verifies exactly
#     the affected modules.
#
# This yields an instant no-op when nothing changed, and a minimal rebuild
# otherwise -- exactly like a normal incremental `make` in a source checkout.

oldest="$(find obj -maxdepth 1 -name '*.checked' -printf '%T@\n' | sort -n | head -1)"
oldest="${oldest%.*}"
OLD_STAMP="$(date -d "@$((oldest - 120))" '+%Y-%m-%d %H:%M:%S')"
DEP_STAMP="$(date -d "@$((oldest - 60))"  '+%Y-%m-%d %H:%M:%S')"

# See the `.packaged` guards in verify.mk: with these markers present and older
# than the checked files, make treats the toolchain and plugin as prebuilt and
# up to date and never tries to rebuild them from the (absent) submodules.
touch .packaged
touch -d "$OLD_STAMP" .fstar.src.touch .fstar.touch .krml.src.touch .krml.touch .plugin.touch
# .depend newer than the sources/touch files (so it is not needlessly
# regenerated) but older than the checked files.
[ -f .depend ] && touch -d "$DEP_STAMP" .depend

changed=0
unchanged=0
while IFS= read -r f; do
  if [ -f "$PKG/$f" ] && cmp -s "$f" "$PKG/$f"; then
    # Valid checked file exists: make this source older so make skips it.
    touch -d "$OLD_STAMP" "$f"
    unchanged=$((unchanged + 1))
  else
    # New or modified: mark it fresh so make re-verifies it (and dependents).
    touch "$f"
    changed=$((changed + 1))
  fi
done < <(find src \( -name '*.fst' -o -name '*.fsti' \))

# Keep the autogen scripts older than their generated .fst so make does not
# needlessly regenerate them (the .fst were compared/aged in the loop above).
find src -name '*.fst.sh' -exec touch -d "$OLD_STAMP" {} +

msg "Seeding done: $unchanged file(s) reused, $changed file(s) to (re)verify."
if [ "$changed" -gt 0 ]; then
  # A changed source set may alter the dependency graph; force regeneration.
  rm -f .depend
fi

# --- Build ----------------------------------------------------------------

if $DO_BUILD; then
  msg "Running: make -j$JOBS $TARGET"
  exec make -j"$JOBS" "$TARGET"
else
  msg "Skipping build (--no-build). Run 'make -j$JOBS $TARGET' when ready."
fi
